LucidVR/opengloves-driver

- LucidGloves/LucidGloves/resources/settings/default.vrsettings
Reverts LucidVR/lucidgloves-openvr#13
> Revert "Delete default.vrsettings"

- .editorconfig
- .gitignore
- LucidGloves/include/Bones.h
- LucidGloves/include/Comm/CommunicationManager.h
- LucidGloves/include/Comm/SerialCommunicationManager.h
- LucidGloves/include/ControllerDriver.h
- LucidGloves/include/DeviceProvider.h
- LucidGloves/src/ControllerDriver.cpp
- LucidGloves/src/ControllerPose.cpp
- LucidGloves/src/DeviceFactory.cpp
- LucidGloves/src/DeviceProvider.cpp
- LucidGloves/src/DriverLog.cpp
- LucidGloves/src/Quaternion.cpp
closing #18 
making the issue slightly more general: would also be good to use const references rather than passing by value.
> Code style

- LucidGloves/include/Comm/SerialCommunicationManager.h
- LucidGloves/src/Comm/SerialCommunicationManager.cpp
- LucidGloves/src/ControllerPose.cpp
> fix crash when arduino disconnects prematurely

- LucidGloves/include/DeviceConfiguration.h
- LucidGloves/lucidgloves/resources/settings/default.vrsettings
- LucidGloves/src/ControllerDriver.cpp
- LucidGloves/src/DeviceProvider.cpp
> Added configuration for left and right hand enabled

- LucidGloves/lucidgloves/resources/settings/default.vrsettings
- LucidGloves/src/DeviceProvider.cpp
> split flip into rotation and position

- LucidGloves/lucidgloves/resources/input/lucidgloves_profile.json
- LucidGloves/src/ControllerDriver.cpp
> impl b + pinch actions

- LucidGloves/LucidGloves.vcxproj
- LucidGloves/include/Communication/CommunicationManager.h
- LucidGloves/include/Communication/SerialCommunicationManager.h
- LucidGloves/include/ControllerPose.h
- LucidGloves/include/DeviceConfiguration.h
- LucidGloves/include/DeviceDriver/DeviceDriver.h
- LucidGloves/include/DeviceDriver/KnuckleDriver.h
- LucidGloves/include/DeviceDriver/LucidGloveDriver.h
- LucidGloves/include/DeviceProvider.h
- LucidGloves/lucidgloves/resources/settings/default.vrsettings
- LucidGloves/src/Communication/SerialCommunicationManager.cpp
- LucidGloves/src/ControllerPose.cpp
- LucidGloves/src/DeviceDriver/KnuckleDriver.cpp
- LucidGloves/src/DeviceDriver/LucidGloveDriver.cpp
- LucidGloves/src/DeviceProvider.cpp
- README.md
This pull request will add support for device emulation to the driver - something that will we believe will be necersarry for device emulation. It will also include a refactor of the configuration file to support this.
closes #49
> Device emulation

- .gitmodules
- CMakeLists.txt
- include/Communication/CommunicationManager.h
- include/Communication/SerialCommunicationManager.h
- include/ControllerPose.h
- include/DeviceConfiguration.h
- include/DeviceDriver/KnuckleDriver.h
- include/DeviceDriver/LucidGloveDriver.h
- include/DeviceProvider.h
- include/Encode/EncodingManager.h
- include/Encode/LegacyEncodingManager.h
- include/Quaternion.h
- openglove/resources/settings/default.vrsettings
- src/Communication/SerialCommunicationManager.cpp
- src/ControllerPose.cpp
- src/DeviceDriver/KnuckleDriver.cpp
- src/DeviceDriver/LucidGloveDriver.cpp
- src/DeviceFactory.cpp
- src/DeviceProvider.cpp
- src/Encode/LegacyEncodingManager.cpp
- src/Quaternion.cpp
Refactor config file & handling of controller pose config to have explicit offsets for both left and right hand (instead of one for each hand with mirroring)
Also tidies up some includes
> Refactor configuration handling

- NOTICE.md
- README.md
This aims to make the build instructions more clear to follow than the previous readme, as well as reformat the information into a clearer format
> readme updates

- openglove/resources/settings/default.vrsettings
config changes for soon to come ui
> update configuration for ui

- include/Encode/EncodingManager.h
- src/Communication/BTSerialCommunicationManager.cpp
- src/Communication/SerialCommunicationManager.cpp
- src/Encode/LegacyEncodingManager.cpp
Fixes the issue of errors caused by improper formatting to the encoding manager.
Changes by @lucas-vrtech  and @danwillm ,
Tested on @lucas-vrtech's rig while @danwillm is unavailable
> Encoder tweaks

- src/Quaternion.cpp
Testing and tweaking on @lucas-vrtech's rig while @danwillm is unavailable
> New EulerToQuaternion

- include/ControllerPose.h
- src/ControllerPose.cpp
Thank you to Ief and Nadia Mayer for testing with Vive wands!
> Set up auto opted out controller discovery (vive wands)

- src/Communication/BTSerialCommunicationManager.cpp
- src/ControllerPose.cpp
Bluetooth reliability updates:
* Fixed an issue caused by blank packets in the Bluetooth buffer
* Fixed an issue with multiple devices caused by the name always being accepted
> Bluetooth reliability updates

- src/Communication/BTSerialCommunicationManager.cpp
- src/ControllerPose.cpp
Patched updates: 
* Fixed an issue caused by blank packets in the Bluetooth buffer
* Fixed an issue with multiple devices caused by the name always being accepted
v0.3 Features:
* Added support for Bluetooth Serial communication
- This is an _experimental feature_ as it has not been tested on all configurations yet.
* Driver has now been renamed to opengloves. Still the official driver of Lucidgloves and Fngrs.
* Added automatic Vive wand detection so that override settings are no longer needed.
v0.3 Tweaks:
* Configuration settings have been changed to work over UI
* Fixed crashes caused by improper encoding
* Improved rotation offsets run faster and possibly more reliably
>  Release: v0.3 (Patched)

- README.md
Drafted until the steam release is up
> Add steam store info to readme

- openglove/resources/settings/default.vrsettings
Some people may have been confused on what "Device Driver" meant as it didn't specify it was emulation. This PR clarifies that title and a couple other small nitpicks.
> Clarify UI setting titles

- .clang-format
Add clang format for a default code style
> Add clang format

- BUILDING.md
The process to link the driver with steamvr is covered in the following sections
> Remove add to steam step

- README.md
OpenGlove -> OpenGloves
Discord Server -> Community Discord Server
Tiny readme changes
> Readme naming consistencies

- include/DeviceConfiguration.h
- openglove/resources/settings/default.vrsettings
- src/ControllerPose.cpp
- src/DeviceProvider.cpp
Rename the pose offset setting to be pose time offset, because it originally wasn't very clear what this setting was supposed to do.
> pose_offset -> pose_time_offset

- overlay/main.cpp
- src/DeviceDriver/KnuckleDriver.cpp
- src/DeviceDriver/LucidGloveDriver.cpp
Changes manufacturer name to "LucidVR"
> Fix inconsistent manufacturer name causing issues with lucid glove device and controller discovery

- README.md
Update to features in readme. Should only be merged in right before v0.4 release
> Readme features update v0.4

- include/Bones.h
- include/Communication/BTSerialCommunicationManager.h
- include/Communication/CommunicationManager.h
- include/Communication/SerialCommunicationManager.h
- include/Encode/EncodingManager.h
- src/Bones.cpp
- src/Communication/BTSerialCommunicationManager.cpp
- src/Communication/SerialCommunicationManager.cpp
- src/DeviceDriver/KnuckleDriver.cpp
- src/DeviceDriver/LucidGloveDriver.cpp
- src/Encode/AlphaEncodingManager.cpp
- src/Encode/LegacyEncodingManager.cpp
Cleanups some aspects of the communication managers to support reconnection + late connection.
> Communication manager cleanup

- include/Communication/BTSerialCommunicationManager.h
- include/Communication/SerialCommunicationManager.h
- include/DeviceConfiguration.h
- include/DeviceDriver/KnuckleDriver.h
- include/DeviceDriver/LucidGloveDriver.h
- include/Encode/AlphaEncodingManager.h
- include/Encode/LegacyEncodingManager.h
- src/Communication/SerialCommunicationManager.cpp
- src/DeviceProvider.cpp
Added constant strings for section headings
Corrected incorrect usage of strcat
> Cherry-picked improvements from PR #130

- include/Communication/BTSerialCommunicationManager.h
- include/Communication/SerialCommunicationManager.h
- include/DeviceConfiguration.h
- include/DeviceDriver/DeviceDriver.h
- include/DeviceDriver/KnuckleDriver.h
- include/DeviceDriver/LucidGloveDriver.h
- include/DeviceProvider.h
- src/Communication/BTSerialCommunicationManager.cpp
- src/Communication/CommunicationManager.cpp
- src/Communication/SerialCommunicationManager.cpp
- src/DeviceConfiguration.cpp
- src/DeviceDriver/DeviceDriver.cpp
- src/DeviceDriver/KnuckleDriver.cpp
- src/DeviceDriver/LucidGloveDriver.cpp
- src/DeviceProvider.cpp
- src/ForceFeedback.cpp
Also refactored various files' include statements
> Moved shared device driver logic to DeviceDriver

- include/Util/Quaternion.h
- src/Calibration.cpp
- src/ControllerPose.cpp
- src/DeviceProvider.cpp
- src/Util/Quaternion.cpp
Aims to fix the subtle lag between the controller and the glove when rotating.
Also moves quaternion to util folder.
> Angular velocity relative to glove

- include/DeviceDriver/DeviceDriver.h
- src/DeviceDriver/DeviceDriver.cpp
> Update poses in thread

- include/Bones.h
- include/Util/AnimLoader.h
- src/Bones.cpp
- src/DeviceDriver/DeviceDriver.cpp
- src/Util/AnimLoader.cpp
Splits up the animation loader and bone animator
> Split up animation loader and bone animator

- README.md
- docs/Building.md
- docs/Compatibility.md
- docs/Installation.md
Adds additional info on some parts of the driver to the docs and readme.
> Doc & Readme changes

- src/DeviceDriver/KnuckleDriver.cpp
Grip force is a scalar, not boolean, so update it as so.
> Update grip force as scalar

- include/Util/Quaternion.h
- src/Bones.cpp
- src/Calibration.cpp
- src/ControllerPose.cpp
- src/DeviceProvider.cpp
- src/Util/Quaternion.cpp
Cleans up quaternions a little and hopefully fixes calibration problems after restarting steamvr
> Fixup pose calibration

- include/Communication/NamedPipeCommunicationManager.h
- include/Encode/EncodingManager.h
- include/Util/NamedPipeListener.h
- src/Communication/NamedPipeCommunicationManager.cpp
- src/ControllerDiscovery.cpp
- src/ControllerPose.cpp
- src/DeviceProvider.cpp
- src/Encode/AlphaEncodingManager.cpp
- src/Encode/LegacyEncodingManager.cpp
- src/ForceFeedback.cpp
Allows input named pipes to have multiple versions
> Version input named pipes 

- overlay/main.cpp
I think this is what was causing the problems from ltt...
> Fix rare case where controllers might not be found
