- LucidGloves/include/Comm/SerialCommunicationManager.h
- LucidGloves/include/ControllerDriver.h
- LucidGloves/include/ControllerPose.h
- LucidGloves/include/Quaternion.h
- LucidGloves/src/ControllerDriver.cpp
- LucidGloves/src/ControllerPose.cpp
- LucidGloves/src/DeviceFactory.cpp
- LucidGloves/src/Quaternion.cpp
closes #21
1. Use const references instead of passing by value in Quaternion
2. ControllerPose could do with some commenting/refactoring, updated ControllerPose to reflact that
> refactor to include const references instead of pass by value, tidy controller pose, init member variables

- LucidGloves/include/ControllerDriver.h
- LucidGloves/src/ControllerDriver.cpp
For some reason, SteamVR doesn't give any info to devices on whether they are still active if it doesn't detect a headset. This is kind of a work around for making sure that we have actually activated a device, but it might be sensible to investigate more cleaner solutions.
> fix crash occurring when no headset is connected

- BUILDING.md
Added instructions to build into a seperate folder and not into the project
root. This allows one to easily clean the project by deleting a single
folder.
Added instructions for compiling the built project files with cmake
instead of opening visual studio and building in there. Allows people to
compile from command line. Its also possible to install the VC++
compiler without Visual Studio IDE (listed as "Build Tools for Visual
Studio" on Microsoft's download page)
> Updated building instructions

- src/DeviceDriver/KnuckleDriver.cpp
- src/DeviceDriver/LucidGloveDriver.cpp
- src/DriverLog.cpp
This PR fixes compiling with gcc, where there were incorrect decalarations of enums, which weren't picked up by msvc.
#65
> GCC compiler errors

- src/Communication/BTSerialCommunicationManager.cpp
Disconnects the windows socket when shutting down the driver. May prevent issues with repeated startups.
> Bugfix btserial disconnect

- CMakeLists.txt
- include/Communication/BTSerialCommunicationManager.h
- include/ControllerPose.h
The previous bluetooth implementation used msvc comment pragma to link the required windows libraries for bluetooth.
This PR changes this to link them in the cmake, as well as fix some incorrect syntax which msvc didn't pick up on.
> Fix mingw link errors

- include/DeviceConfiguration.h
- include/DeviceProvider.h
- include/Encode/AlphaEncodingManager.h
- openglove/resources/settings/default.vrsettings
- src/DeviceProvider.cpp
- src/Encode/AlphaEncodingManager.cpp
Alpha encoding uses the wasted data in the delimiter from legacy to allow for optional arguments and redundancy over smaller packets.
> Alphabetic Encoding Manager

- overlay/main.cpp
Before, the overlay was not taking the handedness of Vive trackers. This PR should fix that.
> Fix overlay vive trackers

- src/DeviceDriver/KnuckleDriver.cpp
One line change - Tracking system name is used by openvr space calibrator and would offset double the amount. Removing the tracking system property fixes this.
> Fix use with openvr space calibrator

- src/Encode/AlphaEncodingManager.cpp
Joystick X-axis was using E instead of F, which meant the pinky was controlling the joystick.
This is a one-line fix to that.
> Fix joystick for alpha encoding manager

- CMakeLists.txt
- include/DeviceProvider.h
- overlay/main.cpp
- src/DeviceProvider.cpp
People were having issues with the overlay being started thru steam/trying to start it when the ui configuration interface was open. This PR changes this to start the overlay up in the driver.
> Init overlay/background process via driver

- README.md
Current link for discord in the readme is invalid, this will update it to a static link that should never need to change (as long as it stays over 30 boosts)
> Update discord link to static link

- CMakeLists.txt
Adds `setupapi` to list of link libraries to fix issues with SteamVR error code 126 for some users
> Fix missing library

- include/Communication/BTSerialCommunicationManager.h
- src/Communication/BTSerialCommunicationManager.cpp
Currently on `develop`, a lot of the function names for the BTSerial manager include the text "ESP32", along with the printouts. As OpenGloves seeks to be open to as much hardware as possible, it is in the project's best interest to generalize these.
> Generalize BTSerial function signatures

- include/DeviceConfiguration.h
- openglove/resources/settings/default.vrsettings
- src/Communication/SerialCommunicationManager.cpp
- src/DeviceProvider.cpp
Added configuration for baud rate within the serial communication protocol. Defaulting to previous value of 115200.
This PR is to address my feature request #119
> Added configuration for baud rate

- src/Encode/AlphaEncodingManager.cpp
Updated a comment with the menu and calibration letters, and optimized the `getArgumentSubstring` helper to avoid a subsequent call to `substr`
> Minor tweaks to AlphaEncodingManager.cpp

- src/Encode/AlphaEncodingManager.cpp
The comments in Alpha Encoding had the indices for each finger backward. This quick PR just puts them in the correct order.
> Fix incorrectly documented finger orders in alpha encoding

- include/Calibration.h
- include/DeviceConfiguration.h
- include/Encode/AlphaEncodingManager.h
- include/Encode/EncodingManager.h
- include/Encode/LegacyEncodingManager.h
- include/Quaternion.h
- overlay/main.cpp
- overlay/main.h
- src/Calibration.cpp
- src/Communication/BTSerialCommunicationManager.cpp
- src/Communication/SerialCommunicationManager.cpp
- src/DeviceDriver/KnuckleDriver.cpp
- src/DeviceDriver/LucidGloveDriver.cpp
- src/DeviceProvider.cpp
- src/Encode/AlphaEncodingManager.cpp
- src/Encode/LegacyEncodingManager.cpp
- src/Quaternion.cpp
- src/Util/NamedPipe.cpp
A lot of minor tweaks like adding explicit casting, and one bigger tweak: Added an enum for storing the `'A'`/`'B'` values instead of hard-coding everywhere
> Removed all warnings from VS compilation, and updated AlphaEncodingManager to use enum

- openglove/resources/settings/default.vrsettings
Results for this based on the poll in the discord server. 
As of 12 minutes into the poll, 31 people voted for 4095 as analog max, 3 people voted for 1023 as default
> Make 4095 the default analog max

- include/Calibration.h
- include/ControllerPose.h
- include/DeviceConfiguration.h
- include/Util/NamedPipeListener.h
- openglove/resources/settings/default.vrsettings
- src/Calibration.cpp
- src/ControllerPose.cpp
- src/DeviceDriver/DeviceDriver.cpp
- src/DeviceProvider.cpp
Hardware button interacts with the calibration process if done through the UI and the pin is floating. This pr adds:
1. A config option for enabling the button for pose calibration
2. A check for making sure the same method started the calibration when ending
Some additional logging for named pipes.
> Pose calibration bugfix

- include/Util/Logic.h
- src/Communication/BTSerialCommunicationManager.cpp
- src/Util/Logic.cpp
Currently, if the send for bluetooth fails, the communication with the device will stop completely without the ability to reconnect. This PR adds in attempts to retry sending to the device at a giving interval to help prevent completely disconnecting.
> Retry bluetooth send on error

- include/Util/NamedPipeListener.h
- overlay/main.h
A recent change introduced an inconsistency with the named pipe struct members, causing reads to fail. This change reverts that back.
> Fix controller discovery pipe

- include/Communication/NamedPipeCommunicationManager.h
- src/Communication/CommunicationManager.cpp
For some communications methods, there might not be an encoding manager. This causes problems when trying to send data, as it would use the encoding manager, which might be nullptr. This PR adds a check to make sure that isn't the case.
> Ensure encoding manager is valid before using

- include/DeviceDriver/KnuckleDriver.h
- openglove/resources/settings/default.vrsettings
- src/DeviceDriver/KnuckleDriver.cpp
- src/DeviceProvider.cpp
Allow some degree of thumb motion in index-emulated games, by setting (capacitive) touch on the A button when the thumb is pushed beyond a certain threshold.
> Thumb approximation for Index Emulation

- openglove/resources/settings/default.vrsettings
The hardware calibration toggle was a little bit buried under the less used pose settings, so moved it to the top.
> Move calibration button toggle to the top of the pose settings section

- include/Bones.h
- src/Bones.cpp
Previously we would get the bones based on their index, now we get them on their name. Also fix some lerping issues between keyframes for smoother curls.
> Refactor bones to interpolate between keyframes and have wider support for animation files

- include/Bones.h
- src/Bones.cpp
Previously, we didn't have a check to make sure that the flexion values were valid before trying to use them for calculations, this change passes bones by reference, as well as checking to make sure that we actually have a value within range to use, otherwise it skips the bones, so it remains where it is.
> Ensure valid values when calculating bone transforms

- src/Communication/SerialCommunicationManager.cpp
Fixes a bug observable in 0.4.2 which causes serial communication on ESP32's (cp210x) to be very laggy over USB.
This is fixed by removing the buffer purge, which may be fixed later on.
> Bugfix serial lag

- src/Calibration.cpp
Recently a change was made that would use radians in a quaternion to euler conversion, rather than degrees. This change broke calibration.
This pr sets the calibration settings to degrees when saving.
> Use degrees in pose settings

- include/DeviceConfiguration.h
- include/Encode/EncodingManager.h
- openglove/resources/settings/default.vrsettings
- src/DeviceDriver/KnuckleDriver.cpp
- src/DeviceProvider.cpp
- src/Encode/AlphaEncodingManager.cpp
- src/Encode/LegacyEncodingManager.cpp
dumb-dumb change to trigger behavior to alleviate some headaches in certain applications but especially overlays. 
This removes the analog trigger behavior, but what marginal benefits using your index finger as a trigger brings is outweighed by the issues of having the controller trigger constantly triggering unintentionally in most usage scenarios. 
This should be seen as a temporary feature loss until there is some consensus and solution on how to better replicate the analog trigger that doesn't make the gloves annoying to use.
> expanding knuckle emulation trigger behavior

- include/Communication/CommunicationManager.h
- include/Communication/SerialCommunicationManager.h
- src/Communication/CommunicationManager.cpp
- src/Communication/SerialCommunicationManager.cpp
Disconnect from device before joining the thread. This might result in a error being thrown as we now close the handle while before joining the thread, more testing might be required.
> Cancel operations before attempting to join thread
